### PR TITLE
Adding change

### PR DESCRIPTION
**Pull request by bsrz**

### CODE REVIEW

**Comment by bsrz** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/bsarrazin/soothe/pull-request/3/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=bsarrazin/soothe)

**Comment by bsrz** [comment]
Rejected

[Rejected with PullApprove](https://pullapprove.com/bsarrazin/soothe/pull-request/3/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=bsarrazin/soothe)

**Comment by bsrz** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/bsarrazin/soothe/pull-request/3/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=bsarrazin/soothe)

**Comment by Mackarous** [comment]
Approved 🎉

**Comment by Mackarous** [comment]
Rejected

[Rejected with PullApprove](https://pullapprove.com/bsarrazin/soothe/pull-request/3/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=bsarrazin/soothe)

**Comment by Mackarous** [comment]
Approve

**Comment by bsrz** [comment]
Approved

**Comment by Mackarous** [comment]
approved

**Comment by Mackarous** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/bsarrazin/soothe/pull-request/3/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=bsarrazin/soothe)

**Comment by bsrz** [comment]
Rejected

[Rejected with PullApprove](https://pullapprove.com/bsarrazin/soothe/pull-request/3/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=bsarrazin/soothe)

**Comment by bsrz** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/bsarrazin/soothe/pull-request/3/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=bsarrazin/soothe)

**Pull request closed without merging**
